# Setup
title:        TreeHole
tagline:      让记录成为一种习惯
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       张英伟
  url:        http://blog.zhangyingwei.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown